
pipeline {
    agent any
    stages {
        // continious integration
        stage('install dependencies') { 
            steps {
                dir("ui"){
                    sh 'npm install' 
                }
           }
        }
        stage('Test') { 
            steps {
                echo "test"
            }
        }
        stage('Build') { 
            steps {
                dir("ui"){
                    sh 'npm run build' 
                }
            } 
        }
        // continious deployment
        stage('Build') { 
            steps {
                dir("ui"){
                    sh 'scp -i /home/ubuntu/aws-fedora.pem build/* ubuntu@13.234.116.70:/var/www/html' 
                }
            } 
        }

    }
}

