
pipeline {
    agent any
    stages {
        stage('install dependencies') { 
            steps {
                dir("ui"){
                    sh 'npm install' 
                }
           }
        }
        stage('Test') { 
            steps {
                echo "test"
            }
        }
         stage('Build') { 
            steps {
                dir("ui"){
                    sh 'npm run build' 
                }
            } 
        }
    }
}

